### ISSUE TITLE
数据预测

### ISSUE THREAD

**Issue by jarvii218** [Cwuwhu/FCD-GAN-pytorch#7]
您好，请问WSSS部分是否只有训练模型的部分，如果我想进行预测自己的数据集，是需要自己编写测试脚本吗？

**Comment by Cwuwhu** [comment]
其实WSSS部分最下面有测试脚本，自己写也可以，很简单



***@***.***
 
发件人： jarvii218
发送时间： 2023-08-28 16:50
收件人： Cwuwhu/FCD-GAN-pytorch
抄送： Subscribed
主题： [Cwuwhu/FCD-GAN-pytorch] 数据预测 (Issue #7)
您好，请问WSSS部分是否只有训练模型的部分，如果我想进行预测自己的数据集，是需要自己编写测试脚本吗？

**Comment by jarvii218** [comment]
是的，已经看到了测试部分，感谢回复

发自我的 iPhone

在 2023年8月29日，11:07，Cwuwhu ***@***.***> 写道：

﻿

其实WSSS部分最下面有测试脚本，自己写也可以，很简单



***@***.***

发件人： jarvii218
发送时间： 2023-08-28 16:50
收件人： Cwuwhu/FCD-GAN-pytorch
抄送： Subscribed
主题： [Cwuwhu/FCD-GAN-pytorch] 数据预测 (Issue #7)
您好，请问WSSS部分是否只有训练模型的部分，如果我想进行预测自己的数据集，是需要自己编写测试脚本吗？

**Comment by jarvii218** [comment]
想再请教下，USSS无监督部分训练的时候也需要输入label图像吗？不输入后面S和Dmodel训练似乎会有问题，这和我理解的无监督不太一样？

在 2023年8月29日，11:36，贾 玮 ***@***.***> 写道：

﻿ 是的，已经看到了测试部分，感谢回复

发自我的 iPhone

在 2023年8月29日，11:07，Cwuwhu ***@***.***> 写道：

﻿

其实WSSS部分最下面有测试脚本，自己写也可以，很简单



***@***.***

发件人： jarvii218
发送时间： 2023-08-28 16:50
收件人： Cwuwhu/FCD-GAN-pytorch
抄送： Subscribed
主题： [Cwuwhu/FCD-GAN-pytorch] 数据预测 (Issue #7)
您好，请问WSSS部分是否只有训练模型的部分，如果我想进行预测自己的数据集，是需要自己编写测试脚本吗？

**Comment by Cwuwhu** [comment]
输入的label图像是为了做精度评价，如果你没有label图像随便生成一个图像就行。这个代码本意是用来做研究的，没做的那么灵活



***@***.***
 
发件人： JohnnyWick
发送时间： 2023-08-31 09:38
收件人： Cwuwhu/FCD-GAN-pytorch
抄送： Cwuwhu; Comment
主题： Re: [Cwuwhu/FCD-GAN-pytorch] 数据预测 (Issue #7)
想再请教下，USSS无监督部分训练的时候也需要输入label图像吗？不输入后面S和Dmodel训练似乎会有问题，这和我理解的无监督不太一样？ 

在 2023年8月29日，11:36，贾 玮 ***@***.***> 写道： 

﻿ 是的，已经看到了测试部分，感谢回复 

发自我的 iPhone 

在 2023年8月29日，11:07，Cwuwhu ***@***.***> 写道： 

﻿ 

其实WSSS部分最下面有测试脚本，自己写也可以，很简单 



***@***.*** 

发件人： jarvii218 
发送时间： 2023-08-28 16:50 
收件人： Cwuwhu/FCD-GAN-pytorch 
抄送： Subscribed 
主题： [Cwuwhu/FCD-GAN-pytorch] 数据预测 (Issue #7) 
您好，请问WSSS部分是否只有训练模型的部分，如果我想进行预测自己的数据集，是需要自己编写测试脚本吗？

**Comment by jarvii218** [comment]
好的，因为我尝试不输入label图像了，也训练了三个模型，但是看见输出路程里在计算精度和loss值，如果不输入label这些值肯定也是空的，我以为需要根据label来评估这些参数后再进一步迭代。不需要的话就是我理解的无监督了，非常感谢您的回答！

发自我的 iPhone

在 2023年8月31日，17:07，Cwuwhu ***@***.***> 写道：

﻿

输入的label图像是为了做精度评价，如果你没有label图像随便生成一个图像就行。这个代码本意是用来做研究的，没做的那么灵活



***@***.***

发件人： JohnnyWick
发送时间： 2023-08-31 09:38
收件人： Cwuwhu/FCD-GAN-pytorch
抄送： Cwuwhu; Comment
主题： Re: [Cwuwhu/FCD-GAN-pytorch] 数据预测 (Issue #7)
想再请教下，USSS无监督部分训练的时候也需要输入label图像吗？不输入后面S和Dmodel训练似乎会有问题，这和我理解的无监督不太一样？

在 2023年8月29日，11:36，贾 玮 ***@***.***> 写道：

﻿ 是的，已经看到了测试部分，感谢回复

发自我的 iPhone

在 2023年8月29日，11:07，Cwuwhu ***@***.***> 写道：

﻿

其实WSSS部分最下面有测试脚本，自己写也可以，很简单



***@***.***

发件人： jarvii218
发送时间： 2023-08-28 16:50
收件人： Cwuwhu/FCD-GAN-pytorch
抄送： Subscribed
主题： [Cwuwhu/FCD-GAN-pytorch] 数据预测 (Issue #7)
您好，请问WSSS部分是否只有训练模型的部分，如果我想进行预测自己的数据集，是需要自己编写测试脚本吗？
